### ISSUE TITLE
Reader URLs

### ISSUE THREAD

**Issue by operatorone** [jb-support/multiple-sitemaps#3]
Hey there! I just wanted to say thank you for the awesome extension. 

I was wondering if you could help me out with creating a sitemap for a specific purpose, like a news archive. When I select the news page and the reader page, only those two show up, but not the news posts. Is there a way to include them in a specific sitemap?

**Comment by operatorone** [comment]
Hello there, I was wondering if you had any suggestions for my request. How long do you think it would take to make the changes and what would be the cost?

**Comment by Flo-JB** [comment]
Hi operatorone,

I am not sure how to implement this without big changes because adding news/event archives don't rely on the page tree. In other words: How can we decide if an included news archive should be indexed or not. What to do with multiple archives etc...

Because of that I think the correct way would be to extend the archive settings with additional sitemap options (like we did in page tree).

In general I think this would be a useful feature for everyone and we can add that in a manageable effort. If you're willing to fund this change, I can schedule an update for next week.

I try to contact you by email
